import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import Script from "next/script";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  
  title: "Dr Shazia Waghoo",
  icons: {
    icon: "/logo.ico", 
  },
  description: "Generated by create next app",
};


// Enhanced metadata for SEO


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* SEO */}
    
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      

        <Navbar />
        {children}
       
        <Footer/>
      </body>
    </html>
  );
}
